using Godot;

namespace Behide.Game;

[InputMap]
public static partial class InputActions;

public static class BuiltinInputActions
{
    public static readonly StringName UiAccept = "ui_accept";
    public static readonly StringName UiSelect = "ui_select";
    public static readonly StringName UiCancel = "ui_cancel";
    public static readonly StringName UiFocusNext = "ui_focus_next";
    public static readonly StringName UiFocusPrev = "ui_focus_prev";
    public static readonly StringName UiLeft = "ui_left";
    public static readonly StringName UiRight = "ui_right";
    public static readonly StringName UiUp = "ui_up";
    public static readonly StringName UiDown = "ui_down";
    public static readonly StringName UiPageUp = "ui_page_up";
    public static readonly StringName UiPageDown = "ui_page_down";
    public static readonly StringName UiHome = "ui_home";
    public static readonly StringName UiEnd = "ui_end";
    public static readonly StringName UiCut = "ui_cut";
    public static readonly StringName UiCopy = "ui_copy";
    public static readonly StringName UiPaste = "ui_paste";
    public static readonly StringName UiUndo = "ui_undo";
    public static readonly StringName UiRedo = "ui_redo";
    public static readonly StringName UiTextCompletionQuery = "ui_text_completion_query";
    public static readonly StringName UiTextNewline = "ui_text_newline";
    public static readonly StringName UiTextNewlineBlank = "ui_text_newline_blank";
    public static readonly StringName UiTextNewlineAbove = "ui_text_newline_above";
    public static readonly StringName UiTextIndent = "ui_text_indent";
    public static readonly StringName UiTextDedent = "ui_text_dedent";
    public static readonly StringName UiTextBackspace = "ui_text_backspace";
    public static readonly StringName UiTextBackspaceWord = "ui_text_backspace_word";
    public static readonly StringName UiTextBackspaceWordMacos = "ui_text_backspace_word.macos";
    public static readonly StringName UiTextBackspaceAllToLeft = "ui_text_backspace_all_to_left";
    public static readonly StringName UiTextBackspaceAllToLeftMacos = "ui_text_backspace_all_to_left.macos";
    public static readonly StringName UiTextDelete = "ui_text_delete";
    public static readonly StringName UiTextDeleteWord = "ui_text_delete_word";
    public static readonly StringName UiTextDeleteWordMacos = "ui_text_delete_word.macos";
    public static readonly StringName UiTextDeleteAllToRight = "ui_text_delete_all_to_right";
    public static readonly StringName UiTextDeleteAllToRightMacos = "ui_text_delete_all_to_right.macos";
    public static readonly StringName UiTextCaretLeft = "ui_text_caret_left";
    public static readonly StringName UiTextCaretWordLeft = "ui_text_caret_word_left";
    public static readonly StringName UiTextCaretWordLeftMacos = "ui_text_caret_word_left.macos";
    public static readonly StringName UiTextCaretRight = "ui_text_caret_right";
    public static readonly StringName UiTextCaretWordRight = "ui_text_caret_word_right";
    public static readonly StringName UiTextCaretWordRightMacos = "ui_text_caret_word_right.macos";
    public static readonly StringName UiTextCaretUp = "ui_text_caret_up";
    public static readonly StringName UiTextCaretDown = "ui_text_caret_down";
    public static readonly StringName UiTextCaretLineStart = "ui_text_caret_line_start";
    public static readonly StringName UiTextCaretLineStartMacos = "ui_text_caret_line_start.macos";
    public static readonly StringName UiTextCaretLineEnd = "ui_text_caret_line_end";
    public static readonly StringName UiTextCaretLineEndMacos = "ui_text_caret_line_end.macos";
    public static readonly StringName UiTextCaretPageUp = "ui_text_caret_page_up";
    public static readonly StringName UiTextCaretPageDown = "ui_text_caret_page_down";
    public static readonly StringName UiTextCaretDocumentStart = "ui_text_caret_document_start";
    public static readonly StringName UiTextCaretDocumentStartMacos = "ui_text_caret_document_start.macos";
    public static readonly StringName UiTextCaretDocumentEnd = "ui_text_caret_document_end";
    public static readonly StringName UiTextCaretDocumentEndMacos = "ui_text_caret_document_end.macos";
    public static readonly StringName UiTextCaretAddBelow = "ui_text_caret_add_below";
    public static readonly StringName UiTextCaretAddBelowMacos = "ui_text_caret_add_below.macos";
    public static readonly StringName UiTextCaretAddAbove = "ui_text_caret_add_above";
    public static readonly StringName UiTextCaretAddAboveMacos = "ui_text_caret_add_above.macos";
    public static readonly StringName UiTextScrollUp = "ui_text_scroll_up";
    public static readonly StringName UiTextScrollUpMacos = "ui_text_scroll_up.macos";
    public static readonly StringName UiTextScrollDown = "ui_text_scroll_down";
    public static readonly StringName UiTextScrollDownMacos = "ui_text_scroll_down.macos";
    public static readonly StringName UiTextSelectAll = "ui_text_select_all";
    public static readonly StringName UiTextSelectWordUnderCaret = "ui_text_select_word_under_caret";
    public static readonly StringName UiTextAddSelectionForNextOccurrence = "ui_text_add_selection_for_next_occurrence";
    public static readonly StringName UiTextSkipSelectionForNextOccurrence = "ui_text_skip_selection_for_next_occurrence";
    public static readonly StringName UiTextClearCaretsAndSelection = "ui_text_clear_carets_and_selection";
    public static readonly StringName UiTextToggleInsertMode = "ui_text_toggle_insert_mode";
    public static readonly StringName UiTextSubmit = "ui_text_submit";
    public static readonly StringName UiGraphDuplicate = "ui_graph_duplicate";
    public static readonly StringName UiGraphDelete = "ui_graph_delete";
    public static readonly StringName UiFiledialogUpOneLevel = "ui_filedialog_up_one_level";
    public static readonly StringName UiFiledialogRefresh = "ui_filedialog_refresh";
    public static readonly StringName UiFiledialogShowHidden = "ui_filedialog_show_hidden";
    public static readonly StringName UiSwapInputDirection = "ui_swap_input_direction";
}
