name: ⚗️ Tests

on:
  push:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cache
      - uses: actions/cache@v2
        with:
          path: path/to/your/project/Library
          key: Library-Behide-Tests
          restore-keys: |
            Library-Behide-
            Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Test report
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unity Playmode Tests
          path: artifacts/playmode/*.xml
          reporter: jest-junit