name: Tests ⚡

on: push

jobs:
  test:
    runs-on: self-hosted
    steps:
      - run: pwd
      - run: ls -al ../../../
      - run: touch ../../../behide-storage/hello.txt
      - run: echo "Hello" >> ../../../behide-storage/hello.txt